version: '2'

services:
  node:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "8080:8080"
    networks:
      - nodeapp-network

  mongodb:
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
